package com.locationmatching.enums;

public enum LocationType {
	BLANK, HOUSE, APARTMENT, CONDOMINIUM, TOWNHOUSE, OFFICE_BUILDING, PARK, HOSPITAL, CHURCH, BUDDIST_TEMPLE, SYNAGOGUE, MUSEUM, ART_GALLERY, CEMETARY;
}
